apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/ingress/alb
  - ../../base/ingress/nginx

  - ../../base/mysql
  - ../../base/backend
  - ../../base/frontend
  
patches:
  - target:
      group: elbv2.k8s.aws
      version: v1beta1
      kind: IngressClassParams
      name: alb
    patch: |-
      - op: replace
        path: /spec/subnets/ids
        value:
          -
          -