apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-apps-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/hovietvinh/3-Tier-GitOps-CD'
    targetRevision: dev
    path: apps/overlays/dev
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true