name: Deploy root app

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev


jobs:

  eks_deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: ${{ github.event.inputs.environment || 'dev' }}
    env:
      DEPLOY_ENV: ${{ github.event.inputs.environment || 'dev' }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      EKS_CLUSTER_NAME: ${{ vars.EKS_CLUSTER_NAME }}
      AWS_GITHUB_ACTIONS_ROLE_ARN: ${{ secrets.AWS_GITHUB_ACTIONS_ROLE_ARN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Debug OIDC Token Claims (Catch Red-Handed)
        uses: actions/github-script@v7
        with:
          script: |
            const token = await core.getIDToken('sts.amazonaws.com');
            const payload = token.split('.')[1];
            const decoded = Buffer.from(payload, 'base64').toString('utf-8');
            console.log("=== RAW JWT CLAIMS GỬI SANG AWS ===");
            console.log(JSON.parse(decoded));

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@5579c002bb4778aa43395ef1df492868a9a1c83f
        with:
          role-to-assume: ${{ env.AWS_GITHUB_ACTIONS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
        with:
          terraform_version: 1.14.4

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig --name "${EKS_CLUSTER_NAME}" --region "${AWS_REGION}"

      - name: Apply manifests
        working-directory: ./bootstrap
        run: |

          kubectl apply -f root-app-${{ env.DEPLOY_ENV }}.yaml

